apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - installation.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - webhook-configuration.yaml
  - crds/dynamicconfigclasses.json
  - crds/clusterdynamicconfigclasses.json
  - crds/dynamicconfigrenders.json
