apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamic-config-operator
  namespace: dynamic-config
  labels:
    app.kubernetes.io/name: dynamic-config
    app.kubernetes.io/component: operator
